create table wallets (
    id varchar(100) primary key,
    balance bigint not null check (balance >= 0),
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null
);

create table transfers (
    id uuid primary key,
    idempotency_key varchar(200) not null unique,
    request_hash varchar(64) not null,
    from_wallet_id varchar(100) not null references wallets(id),
    to_wallet_id varchar(100) not null references wallets(id),
    amount bigint not null check (amount > 0),
    state varchar(20) not null check (state in ('PENDING', 'PROCESSED', 'FAILED')),
    failure_reason varchar(255),
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null
);

create index idx_transfers_from_wallet_id on transfers(from_wallet_id);
create index idx_transfers_to_wallet_id on transfers(to_wallet_id);

create table ledger_entries (
    id bigint generated by default as identity primary key,
    transfer_id uuid not null references transfers(id),
    wallet_id varchar(100) not null references wallets(id),
    entry_type varchar(20) not null check (entry_type in ('DEBIT', 'CREDIT')),
    amount bigint not null check (amount > 0),
    created_at timestamp with time zone not null,
    constraint uk_ledger_entries_transfer_type unique (transfer_id, entry_type)
);

create index idx_ledger_entries_wallet_created_at on ledger_entries(wallet_id, created_at);
